{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='consumer', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Consumer', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'jetstream.nats.io/v1beta2',
    kind: 'Consumer',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#tls':: d.obj(help="\"A client's TLS certs and keys.\""),
    tls: {
      '#withClientCert':: d.fn(help="\"A client's cert filepath. Should be mounted.\"", args=[d.arg(name='clientCert', type=d.T.string)]),
      withClientCert(clientCert): { spec+: { tls+: { clientCert: clientCert } } },
      '#withClientKey':: d.fn(help="\"A client's key filepath. Should be mounted.\"", args=[d.arg(name='clientKey', type=d.T.string)]),
      withClientKey(clientKey): { spec+: { tls+: { clientKey: clientKey } } },
      '#withRootCas':: d.fn(help='"A list of filepaths to CAs. Should be mounted."', args=[d.arg(name='rootCas', type=d.T.array)]),
      withRootCas(rootCas): { spec+: { tls+: { rootCas: if std.isArray(v=rootCas) then rootCas else [rootCas] } } },
      '#withRootCasMixin':: d.fn(help='"A list of filepaths to CAs. Should be mounted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='rootCas', type=d.T.array)]),
      withRootCasMixin(rootCas): { spec+: { tls+: { rootCas+: if std.isArray(v=rootCas) then rootCas else [rootCas] } } },
    },
    '#withAccount':: d.fn(help='"Name of the account to which the Consumer belongs."', args=[d.arg(name='account', type=d.T.string)]),
    withAccount(account): { spec+: { account: account } },
    '#withAckPolicy':: d.fn(help='"How messages should be acknowledged."', args=[d.arg(name='ackPolicy', type=d.T.string)]),
    withAckPolicy(ackPolicy): { spec+: { ackPolicy: ackPolicy } },
    '#withAckWait':: d.fn(help='"How long to allow messages to remain un-acknowledged before attempting redelivery."', args=[d.arg(name='ackWait', type=d.T.string)]),
    withAckWait(ackWait): { spec+: { ackWait: ackWait } },
    '#withBackoff':: d.fn(help="\"List of durations representing a retry time scale for NaK'd or retried messages.\"", args=[d.arg(name='backoff', type=d.T.array)]),
    withBackoff(backoff): { spec+: { backoff: if std.isArray(v=backoff) then backoff else [backoff] } },
    '#withBackoffMixin':: d.fn(help="\"List of durations representing a retry time scale for NaK'd or retried messages.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='backoff', type=d.T.array)]),
    withBackoffMixin(backoff): { spec+: { backoff+: if std.isArray(v=backoff) then backoff else [backoff] } },
    '#withCreds':: d.fn(help='"NATS user credentials for connecting to servers. Please make sure your controller has mounted the creds on its path."', args=[d.arg(name='creds', type=d.T.string)]),
    withCreds(creds): { spec+: { creds: creds } },
    '#withDeliverGroup':: d.fn(help='"The name of a queue group."', args=[d.arg(name='deliverGroup', type=d.T.string)]),
    withDeliverGroup(deliverGroup): { spec+: { deliverGroup: deliverGroup } },
    '#withDeliverPolicy':: d.fn(help='', args=[d.arg(name='deliverPolicy', type=d.T.string)]),
    withDeliverPolicy(deliverPolicy): { spec+: { deliverPolicy: deliverPolicy } },
    '#withDeliverSubject':: d.fn(help='"The subject to deliver observed messages, when not set, a pull-based Consumer is created."', args=[d.arg(name='deliverSubject', type=d.T.string)]),
    withDeliverSubject(deliverSubject): { spec+: { deliverSubject: deliverSubject } },
    '#withDescription':: d.fn(help='"The description of the consumer."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDurableName':: d.fn(help='"The name of the Consumer."', args=[d.arg(name='durableName', type=d.T.string)]),
    withDurableName(durableName): { spec+: { durableName: durableName } },
    '#withFilterSubject':: d.fn(help='"Select only a specific incoming subjects, supports wildcards."', args=[d.arg(name='filterSubject', type=d.T.string)]),
    withFilterSubject(filterSubject): { spec+: { filterSubject: filterSubject } },
    '#withFilterSubjects':: d.fn(help='"List of incoming subjects, supports wildcards. Available since 2.10."', args=[d.arg(name='filterSubjects', type=d.T.array)]),
    withFilterSubjects(filterSubjects): { spec+: { filterSubjects: if std.isArray(v=filterSubjects) then filterSubjects else [filterSubjects] } },
    '#withFilterSubjectsMixin':: d.fn(help='"List of incoming subjects, supports wildcards. Available since 2.10."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='filterSubjects', type=d.T.array)]),
    withFilterSubjectsMixin(filterSubjects): { spec+: { filterSubjects+: if std.isArray(v=filterSubjects) then filterSubjects else [filterSubjects] } },
    '#withFlowControl':: d.fn(help='"Enables flow control."', args=[d.arg(name='flowControl', type=d.T.boolean)]),
    withFlowControl(flowControl): { spec+: { flowControl: flowControl } },
    '#withHeadersOnly':: d.fn(help='"When set, only the headers of messages in the stream are delivered, and not the bodies. Additionally, Nats-Msg-Size header is added to indicate the size of the removed payload."', args=[d.arg(name='headersOnly', type=d.T.boolean)]),
    withHeadersOnly(headersOnly): { spec+: { headersOnly: headersOnly } },
    '#withHeartbeatInterval':: d.fn(help="\"The interval used to deliver idle heartbeats for push-based consumers, in Go's time.Duration format.\"", args=[d.arg(name='heartbeatInterval', type=d.T.string)]),
    withHeartbeatInterval(heartbeatInterval): { spec+: { heartbeatInterval: heartbeatInterval } },
    '#withInactiveThreshold':: d.fn(help='"The idle time an Ephemeral Consumer allows before it is removed."', args=[d.arg(name='inactiveThreshold', type=d.T.string)]),
    withInactiveThreshold(inactiveThreshold): { spec+: { inactiveThreshold: inactiveThreshold } },
    '#withJsDomain':: d.fn(help='"The JetStream domain to use for the consumer."', args=[d.arg(name='jsDomain', type=d.T.string)]),
    withJsDomain(jsDomain): { spec+: { jsDomain: jsDomain } },
    '#withMaxAckPending':: d.fn(help='"Maximum pending Acks before consumers are paused."', args=[d.arg(name='maxAckPending', type=d.T.integer)]),
    withMaxAckPending(maxAckPending): { spec+: { maxAckPending: maxAckPending } },
    '#withMaxDeliver':: d.fn(help='', args=[d.arg(name='maxDeliver', type=d.T.integer)]),
    withMaxDeliver(maxDeliver): { spec+: { maxDeliver: maxDeliver } },
    '#withMaxRequestBatch':: d.fn(help='"The largest batch property that may be specified when doing a pull on a Pull Consumer."', args=[d.arg(name='maxRequestBatch', type=d.T.integer)]),
    withMaxRequestBatch(maxRequestBatch): { spec+: { maxRequestBatch: maxRequestBatch } },
    '#withMaxRequestExpires':: d.fn(help='"The maximum expires duration that may be set when doing a pull on a Pull Consumer."', args=[d.arg(name='maxRequestExpires', type=d.T.string)]),
    withMaxRequestExpires(maxRequestExpires): { spec+: { maxRequestExpires: maxRequestExpires } },
    '#withMaxRequestMaxBytes':: d.fn(help='"The maximum max_bytes value that maybe set when dong a pull on a Pull Consumer."', args=[d.arg(name='maxRequestMaxBytes', type=d.T.integer)]),
    withMaxRequestMaxBytes(maxRequestMaxBytes): { spec+: { maxRequestMaxBytes: maxRequestMaxBytes } },
    '#withMaxWaiting':: d.fn(help='"The number of pulls that can be outstanding on a pull consumer, pulls received after this is reached are ignored."', args=[d.arg(name='maxWaiting', type=d.T.integer)]),
    withMaxWaiting(maxWaiting): { spec+: { maxWaiting: maxWaiting } },
    '#withMemStorage':: d.fn(help='"Force the consumer state to be kept in memory rather than inherit the setting from the stream."', args=[d.arg(name='memStorage', type=d.T.boolean)]),
    withMemStorage(memStorage): { spec+: { memStorage: memStorage } },
    '#withMetadata':: d.fn(help='"Additional Consumer metadata."', args=[d.arg(name='metadata', type=d.T.object)]),
    withMetadata(metadata): { spec+: { metadata: metadata } },
    '#withMetadataMixin':: d.fn(help='"Additional Consumer metadata."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
    withMetadataMixin(metadata): { spec+: { metadata+: metadata } },
    '#withNkey':: d.fn(help='"NATS user NKey for connecting to servers."', args=[d.arg(name='nkey', type=d.T.string)]),
    withNkey(nkey): { spec+: { nkey: nkey } },
    '#withOptStartSeq':: d.fn(help='', args=[d.arg(name='optStartSeq', type=d.T.integer)]),
    withOptStartSeq(optStartSeq): { spec+: { optStartSeq: optStartSeq } },
    '#withOptStartTime':: d.fn(help='"Time format must be RFC3339."', args=[d.arg(name='optStartTime', type=d.T.string)]),
    withOptStartTime(optStartTime): { spec+: { optStartTime: optStartTime } },
    '#withPinnedTtl':: d.fn(help='"TTL for pinned client when using pinned_client priority policy."', args=[d.arg(name='pinnedTtl', type=d.T.string)]),
    withPinnedTtl(pinnedTtl): { spec+: { pinnedTtl: pinnedTtl } },
    '#withPreventDelete':: d.fn(help='"When true, the managed Consumer will not be deleted when the resource is deleted."', args=[d.arg(name='preventDelete', type=d.T.boolean)]),
    withPreventDelete(preventDelete): { spec+: { preventDelete: preventDelete } },
    '#withPreventUpdate':: d.fn(help='"When true, the managed Consumer will not be updated when the resource is updated."', args=[d.arg(name='preventUpdate', type=d.T.boolean)]),
    withPreventUpdate(preventUpdate): { spec+: { preventUpdate: preventUpdate } },
    '#withPriorityGroups':: d.fn(help='"List of priority groups for the consumer. For now, only one group is supported."', args=[d.arg(name='priorityGroups', type=d.T.array)]),
    withPriorityGroups(priorityGroups): { spec+: { priorityGroups: if std.isArray(v=priorityGroups) then priorityGroups else [priorityGroups] } },
    '#withPriorityGroupsMixin':: d.fn(help='"List of priority groups for the consumer. For now, only one group is supported."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='priorityGroups', type=d.T.array)]),
    withPriorityGroupsMixin(priorityGroups): { spec+: { priorityGroups+: if std.isArray(v=priorityGroups) then priorityGroups else [priorityGroups] } },
    '#withPriorityPolicy':: d.fn(help='"Priority policy for consumer (pinned_client, overflow, prioritized, or none)."', args=[d.arg(name='priorityPolicy', type=d.T.string)]),
    withPriorityPolicy(priorityPolicy): { spec+: { priorityPolicy: priorityPolicy } },
    '#withRateLimitBps':: d.fn(help='"Rate at which messages will be delivered to clients, expressed in bit per second."', args=[d.arg(name='rateLimitBps', type=d.T.integer)]),
    withRateLimitBps(rateLimitBps): { spec+: { rateLimitBps: rateLimitBps } },
    '#withReplayPolicy':: d.fn(help='"How messages are sent."', args=[d.arg(name='replayPolicy', type=d.T.string)]),
    withReplayPolicy(replayPolicy): { spec+: { replayPolicy: replayPolicy } },
    '#withReplicas':: d.fn(help='"When set do not inherit the replica count from the stream but specifically set it to this amount."', args=[d.arg(name='replicas', type=d.T.integer)]),
    withReplicas(replicas): { spec+: { replicas: replicas } },
    '#withSampleFreq':: d.fn(help='"What percentage of acknowledgements should be samples for observability."', args=[d.arg(name='sampleFreq', type=d.T.string)]),
    withSampleFreq(sampleFreq): { spec+: { sampleFreq: sampleFreq } },
    '#withServers':: d.fn(help='"A list of servers for creating consumer."', args=[d.arg(name='servers', type=d.T.array)]),
    withServers(servers): { spec+: { servers: if std.isArray(v=servers) then servers else [servers] } },
    '#withServersMixin':: d.fn(help='"A list of servers for creating consumer."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servers', type=d.T.array)]),
    withServersMixin(servers): { spec+: { servers+: if std.isArray(v=servers) then servers else [servers] } },
    '#withStreamName':: d.fn(help='"The name of the Stream to create the Consumer in."', args=[d.arg(name='streamName', type=d.T.string)]),
    withStreamName(streamName): { spec+: { streamName: streamName } },
    '#withTlsFirst':: d.fn(help='"When true, the KV Store will initiate TLS before server INFO."', args=[d.arg(name='tlsFirst', type=d.T.boolean)]),
    withTlsFirst(tlsFirst): { spec+: { tlsFirst: tlsFirst } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
