{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='stream', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Stream', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'jetstream.nats.io/v1beta2',
    kind: 'Stream',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#consumerLimits':: d.obj(help=''),
    consumerLimits: {
      '#withInactiveThreshold':: d.fn(help='"The duration of inactivity after which a consumer is considered inactive."', args=[d.arg(name='inactiveThreshold', type=d.T.string)]),
      withInactiveThreshold(inactiveThreshold): { spec+: { consumerLimits+: { inactiveThreshold: inactiveThreshold } } },
      '#withMaxAckPending':: d.fn(help='"Maximum number of outstanding unacknowledged messages."', args=[d.arg(name='maxAckPending', type=d.T.integer)]),
      withMaxAckPending(maxAckPending): { spec+: { consumerLimits+: { maxAckPending: maxAckPending } } },
    },
    '#mirror':: d.obj(help='"A stream mirror."'),
    mirror: {
      '#subjectTransforms':: d.obj(help='"List of subject transforms for this mirror."'),
      subjectTransforms: {
        '#withDest':: d.fn(help='"Destination subject."', args=[d.arg(name='dest', type=d.T.string)]),
        withDest(dest): { dest: dest },
        '#withSource':: d.fn(help='"Source subject."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { source: source },
      },
      '#withExternalApiPrefix':: d.fn(help='', args=[d.arg(name='externalApiPrefix', type=d.T.string)]),
      withExternalApiPrefix(externalApiPrefix): { spec+: { mirror+: { externalApiPrefix: externalApiPrefix } } },
      '#withExternalDeliverPrefix':: d.fn(help='', args=[d.arg(name='externalDeliverPrefix', type=d.T.string)]),
      withExternalDeliverPrefix(externalDeliverPrefix): { spec+: { mirror+: { externalDeliverPrefix: externalDeliverPrefix } } },
      '#withFilterSubject':: d.fn(help='', args=[d.arg(name='filterSubject', type=d.T.string)]),
      withFilterSubject(filterSubject): { spec+: { mirror+: { filterSubject: filterSubject } } },
      '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { mirror+: { name: name } } },
      '#withOptStartSeq':: d.fn(help='', args=[d.arg(name='optStartSeq', type=d.T.integer)]),
      withOptStartSeq(optStartSeq): { spec+: { mirror+: { optStartSeq: optStartSeq } } },
      '#withOptStartTime':: d.fn(help='"Time format must be RFC3339."', args=[d.arg(name='optStartTime', type=d.T.string)]),
      withOptStartTime(optStartTime): { spec+: { mirror+: { optStartTime: optStartTime } } },
      '#withSubjectTransforms':: d.fn(help='"List of subject transforms for this mirror."', args=[d.arg(name='subjectTransforms', type=d.T.array)]),
      withSubjectTransforms(subjectTransforms): { spec+: { mirror+: { subjectTransforms: if std.isArray(v=subjectTransforms) then subjectTransforms else [subjectTransforms] } } },
      '#withSubjectTransformsMixin':: d.fn(help='"List of subject transforms for this mirror."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='subjectTransforms', type=d.T.array)]),
      withSubjectTransformsMixin(subjectTransforms): { spec+: { mirror+: { subjectTransforms+: if std.isArray(v=subjectTransforms) then subjectTransforms else [subjectTransforms] } } },
    },
    '#placement':: d.obj(help="\"A stream's placement.\""),
    placement: {
      '#withCluster':: d.fn(help='', args=[d.arg(name='cluster', type=d.T.string)]),
      withCluster(cluster): { spec+: { placement+: { cluster: cluster } } },
      '#withTags':: d.fn(help='', args=[d.arg(name='tags', type=d.T.array)]),
      withTags(tags): { spec+: { placement+: { tags: if std.isArray(v=tags) then tags else [tags] } } },
      '#withTagsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.array)]),
      withTagsMixin(tags): { spec+: { placement+: { tags+: if std.isArray(v=tags) then tags else [tags] } } },
    },
    '#republish':: d.obj(help='"Republish configuration of the stream."'),
    republish: {
      '#withDestination':: d.fn(help='"Messages will be additionally published to this subject."', args=[d.arg(name='destination', type=d.T.string)]),
      withDestination(destination): { spec+: { republish+: { destination: destination } } },
      '#withSource':: d.fn(help='"Messages will be published from this subject to the destination subject."', args=[d.arg(name='source', type=d.T.string)]),
      withSource(source): { spec+: { republish+: { source: source } } },
    },
    '#sources':: d.obj(help="\"A stream's sources.\""),
    sources: {
      '#subjectTransforms':: d.obj(help='"List of subject transforms for this mirror."'),
      subjectTransforms: {
        '#withDest':: d.fn(help='"Destination subject."', args=[d.arg(name='dest', type=d.T.string)]),
        withDest(dest): { dest: dest },
        '#withSource':: d.fn(help='"Source subject."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { source: source },
      },
      '#withExternalApiPrefix':: d.fn(help='', args=[d.arg(name='externalApiPrefix', type=d.T.string)]),
      withExternalApiPrefix(externalApiPrefix): { externalApiPrefix: externalApiPrefix },
      '#withExternalDeliverPrefix':: d.fn(help='', args=[d.arg(name='externalDeliverPrefix', type=d.T.string)]),
      withExternalDeliverPrefix(externalDeliverPrefix): { externalDeliverPrefix: externalDeliverPrefix },
      '#withFilterSubject':: d.fn(help='', args=[d.arg(name='filterSubject', type=d.T.string)]),
      withFilterSubject(filterSubject): { filterSubject: filterSubject },
      '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withOptStartSeq':: d.fn(help='', args=[d.arg(name='optStartSeq', type=d.T.integer)]),
      withOptStartSeq(optStartSeq): { optStartSeq: optStartSeq },
      '#withOptStartTime':: d.fn(help='"Time format must be RFC3339."', args=[d.arg(name='optStartTime', type=d.T.string)]),
      withOptStartTime(optStartTime): { optStartTime: optStartTime },
      '#withSubjectTransforms':: d.fn(help='"List of subject transforms for this mirror."', args=[d.arg(name='subjectTransforms', type=d.T.array)]),
      withSubjectTransforms(subjectTransforms): { subjectTransforms: if std.isArray(v=subjectTransforms) then subjectTransforms else [subjectTransforms] },
      '#withSubjectTransformsMixin':: d.fn(help='"List of subject transforms for this mirror."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='subjectTransforms', type=d.T.array)]),
      withSubjectTransformsMixin(subjectTransforms): { subjectTransforms+: if std.isArray(v=subjectTransforms) then subjectTransforms else [subjectTransforms] },
    },
    '#subjectTransform':: d.obj(help='"SubjectTransform is for applying a subject transform (to matching messages) when a new message is received."'),
    subjectTransform: {
      '#withDest':: d.fn(help='"Destination subject to transform into."', args=[d.arg(name='dest', type=d.T.string)]),
      withDest(dest): { spec+: { subjectTransform+: { dest: dest } } },
      '#withSource':: d.fn(help='"Source subject."', args=[d.arg(name='source', type=d.T.string)]),
      withSource(source): { spec+: { subjectTransform+: { source: source } } },
    },
    '#tls':: d.obj(help="\"A client's TLS certs and keys.\""),
    tls: {
      '#withClientCert':: d.fn(help="\"A client's cert filepath. Should be mounted.\"", args=[d.arg(name='clientCert', type=d.T.string)]),
      withClientCert(clientCert): { spec+: { tls+: { clientCert: clientCert } } },
      '#withClientKey':: d.fn(help="\"A client's key filepath. Should be mounted.\"", args=[d.arg(name='clientKey', type=d.T.string)]),
      withClientKey(clientKey): { spec+: { tls+: { clientKey: clientKey } } },
      '#withRootCas':: d.fn(help='"A list of filepaths to CAs. Should be mounted."', args=[d.arg(name='rootCas', type=d.T.array)]),
      withRootCas(rootCas): { spec+: { tls+: { rootCas: if std.isArray(v=rootCas) then rootCas else [rootCas] } } },
      '#withRootCasMixin':: d.fn(help='"A list of filepaths to CAs. Should be mounted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='rootCas', type=d.T.array)]),
      withRootCasMixin(rootCas): { spec+: { tls+: { rootCas+: if std.isArray(v=rootCas) then rootCas else [rootCas] } } },
    },
    '#withAccount':: d.fn(help='"Name of the account to which the Stream belongs."', args=[d.arg(name='account', type=d.T.string)]),
    withAccount(account): { spec+: { account: account } },
    '#withAllowAtomicPublish':: d.fn(help='"When true, enables atomic batch publishing."', args=[d.arg(name='allowAtomicPublish', type=d.T.boolean)]),
    withAllowAtomicPublish(allowAtomicPublish): { spec+: { allowAtomicPublish: allowAtomicPublish } },
    '#withAllowDirect':: d.fn(help='"When true, allow higher performance, direct access to get individual messages."', args=[d.arg(name='allowDirect', type=d.T.boolean)]),
    withAllowDirect(allowDirect): { spec+: { allowDirect: allowDirect } },
    '#withAllowMsgCounter':: d.fn(help='"When true, enables message counters for the stream."', args=[d.arg(name='allowMsgCounter', type=d.T.boolean)]),
    withAllowMsgCounter(allowMsgCounter): { spec+: { allowMsgCounter: allowMsgCounter } },
    '#withAllowMsgSchedules':: d.fn(help='"When true, enables message scheduling."', args=[d.arg(name='allowMsgSchedules', type=d.T.boolean)]),
    withAllowMsgSchedules(allowMsgSchedules): { spec+: { allowMsgSchedules: allowMsgSchedules } },
    '#withAllowMsgTtl':: d.fn(help='"When true, allows header initiated per-message TTLs. If disabled, then the `NATS-TTL` header will be ignored."', args=[d.arg(name='allowMsgTtl', type=d.T.boolean)]),
    withAllowMsgTtl(allowMsgTtl): { spec+: { allowMsgTtl: allowMsgTtl } },
    '#withAllowRollup':: d.fn(help='"When true, allows the use of the Nats-Rollup header to replace all contents of a stream, or subject in a stream, with a single new message."', args=[d.arg(name='allowRollup', type=d.T.boolean)]),
    withAllowRollup(allowRollup): { spec+: { allowRollup: allowRollup } },
    '#withCompression':: d.fn(help='"Stream specific compression."', args=[d.arg(name='compression', type=d.T.string)]),
    withCompression(compression): { spec+: { compression: compression } },
    '#withCreds':: d.fn(help='"NATS user credentials for connecting to servers. Please make sure your controller has mounted the creds on this path."', args=[d.arg(name='creds', type=d.T.string)]),
    withCreds(creds): { spec+: { creds: creds } },
    '#withDenyDelete':: d.fn(help='"When true, restricts the ability to delete messages from a stream via the API. Cannot be changed once set to true."', args=[d.arg(name='denyDelete', type=d.T.boolean)]),
    withDenyDelete(denyDelete): { spec+: { denyDelete: denyDelete } },
    '#withDenyPurge':: d.fn(help='"When true, restricts the ability to purge a stream via the API. Cannot be changed once set to true."', args=[d.arg(name='denyPurge', type=d.T.boolean)]),
    withDenyPurge(denyPurge): { spec+: { denyPurge: denyPurge } },
    '#withDescription':: d.fn(help='"The description of the stream."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDiscard':: d.fn(help="\"When a Stream reach it's limits either old messages are deleted or new ones are denied.\"", args=[d.arg(name='discard', type=d.T.string)]),
    withDiscard(discard): { spec+: { discard: discard } },
    '#withDiscardPerSubject':: d.fn(help="\"Applies discard policy on a per-subject basis. Requires discard policy 'new' and 'maxMsgs' to be set.\"", args=[d.arg(name='discardPerSubject', type=d.T.boolean)]),
    withDiscardPerSubject(discardPerSubject): { spec+: { discardPerSubject: discardPerSubject } },
    '#withDuplicateWindow':: d.fn(help='"The duration window to track duplicate messages for."', args=[d.arg(name='duplicateWindow', type=d.T.string)]),
    withDuplicateWindow(duplicateWindow): { spec+: { duplicateWindow: duplicateWindow } },
    '#withFirstSequence':: d.fn(help='"Sequence number from which the Stream will start."', args=[d.arg(name='firstSequence', type=d.T.number)]),
    withFirstSequence(firstSequence): { spec+: { firstSequence: firstSequence } },
    '#withJsDomain':: d.fn(help='"The JetStream domain to use for the stream."', args=[d.arg(name='jsDomain', type=d.T.string)]),
    withJsDomain(jsDomain): { spec+: { jsDomain: jsDomain } },
    '#withMaxAge':: d.fn(help="\"Maximum age of any message in the stream, expressed in Go's time.Duration format. Empty for unlimited.\"", args=[d.arg(name='maxAge', type=d.T.string)]),
    withMaxAge(maxAge): { spec+: { maxAge: maxAge } },
    '#withMaxBytes':: d.fn(help='"How big the Stream may be, when the combined stream size exceeds this old messages are removed. -1 for unlimited."', args=[d.arg(name='maxBytes', type=d.T.integer)]),
    withMaxBytes(maxBytes): { spec+: { maxBytes: maxBytes } },
    '#withMaxConsumers':: d.fn(help='"How many Consumers can be defined for a given Stream. -1 for unlimited."', args=[d.arg(name='maxConsumers', type=d.T.integer)]),
    withMaxConsumers(maxConsumers): { spec+: { maxConsumers: maxConsumers } },
    '#withMaxMsgSize':: d.fn(help='"The largest message that will be accepted by the Stream. -1 for unlimited."', args=[d.arg(name='maxMsgSize', type=d.T.integer)]),
    withMaxMsgSize(maxMsgSize): { spec+: { maxMsgSize: maxMsgSize } },
    '#withMaxMsgs':: d.fn(help='"How many messages may be in a Stream, oldest messages will be removed if the Stream exceeds this size. -1 for unlimited."', args=[d.arg(name='maxMsgs', type=d.T.integer)]),
    withMaxMsgs(maxMsgs): { spec+: { maxMsgs: maxMsgs } },
    '#withMaxMsgsPerSubject':: d.fn(help='"The maximum number of messages per subject."', args=[d.arg(name='maxMsgsPerSubject', type=d.T.integer)]),
    withMaxMsgsPerSubject(maxMsgsPerSubject): { spec+: { maxMsgsPerSubject: maxMsgsPerSubject } },
    '#withMetadata':: d.fn(help='"Additional Stream metadata."', args=[d.arg(name='metadata', type=d.T.object)]),
    withMetadata(metadata): { spec+: { metadata: metadata } },
    '#withMetadataMixin':: d.fn(help='"Additional Stream metadata."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
    withMetadataMixin(metadata): { spec+: { metadata+: metadata } },
    '#withMirrorDirect':: d.fn(help='"When true, enables direct access to messages from the origin stream."', args=[d.arg(name='mirrorDirect', type=d.T.boolean)]),
    withMirrorDirect(mirrorDirect): { spec+: { mirrorDirect: mirrorDirect } },
    '#withName':: d.fn(help='"A unique name for the Stream."', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { spec+: { name: name } },
    '#withNkey':: d.fn(help='"NATS user NKey for connecting to servers."', args=[d.arg(name='nkey', type=d.T.string)]),
    withNkey(nkey): { spec+: { nkey: nkey } },
    '#withNoAck':: d.fn(help='"Disables acknowledging messages that are received by the Stream."', args=[d.arg(name='noAck', type=d.T.boolean)]),
    withNoAck(noAck): { spec+: { noAck: noAck } },
    '#withPersistMode':: d.fn(help='"Configures stream persistence settings (async or default)."', args=[d.arg(name='persistMode', type=d.T.string)]),
    withPersistMode(persistMode): { spec+: { persistMode: persistMode } },
    '#withPreventDelete':: d.fn(help='"When true, the managed Stream will not be deleted when the resource is deleted."', args=[d.arg(name='preventDelete', type=d.T.boolean)]),
    withPreventDelete(preventDelete): { spec+: { preventDelete: preventDelete } },
    '#withPreventUpdate':: d.fn(help='"When true, the managed Stream will not be updated when the resource is updated."', args=[d.arg(name='preventUpdate', type=d.T.boolean)]),
    withPreventUpdate(preventUpdate): { spec+: { preventUpdate: preventUpdate } },
    '#withReplicas':: d.fn(help='"How many replicas to keep for each message."', args=[d.arg(name='replicas', type=d.T.integer)]),
    withReplicas(replicas): { spec+: { replicas: replicas } },
    '#withRetention':: d.fn(help='"How messages are retained in the Stream, once this is exceeded old messages are removed."', args=[d.arg(name='retention', type=d.T.string)]),
    withRetention(retention): { spec+: { retention: retention } },
    '#withSealed':: d.fn(help='"Seal an existing stream so no new messages may be added."', args=[d.arg(name='sealed', type=d.T.boolean)]),
    withSealed(sealed): { spec+: { sealed: sealed } },
    '#withServers':: d.fn(help='"A list of servers for creating stream."', args=[d.arg(name='servers', type=d.T.array)]),
    withServers(servers): { spec+: { servers: if std.isArray(v=servers) then servers else [servers] } },
    '#withServersMixin':: d.fn(help='"A list of servers for creating stream."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servers', type=d.T.array)]),
    withServersMixin(servers): { spec+: { servers+: if std.isArray(v=servers) then servers else [servers] } },
    '#withSources':: d.fn(help="\"A stream's sources.\"", args=[d.arg(name='sources', type=d.T.array)]),
    withSources(sources): { spec+: { sources: if std.isArray(v=sources) then sources else [sources] } },
    '#withSourcesMixin':: d.fn(help="\"A stream's sources.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='sources', type=d.T.array)]),
    withSourcesMixin(sources): { spec+: { sources+: if std.isArray(v=sources) then sources else [sources] } },
    '#withStorage':: d.fn(help='"The storage backend to use for the Stream."', args=[d.arg(name='storage', type=d.T.string)]),
    withStorage(storage): { spec+: { storage: storage } },
    '#withSubjectDeleteMarkerTtl':: d.fn(help='"Enables and sets a duration for adding server markers for delete, purge and max age limits."', args=[d.arg(name='subjectDeleteMarkerTtl', type=d.T.string)]),
    withSubjectDeleteMarkerTtl(subjectDeleteMarkerTtl): { spec+: { subjectDeleteMarkerTtl: subjectDeleteMarkerTtl } },
    '#withSubjects':: d.fn(help='"A list of subjects to consume, supports wildcards."', args=[d.arg(name='subjects', type=d.T.array)]),
    withSubjects(subjects): { spec+: { subjects: if std.isArray(v=subjects) then subjects else [subjects] } },
    '#withSubjectsMixin':: d.fn(help='"A list of subjects to consume, supports wildcards."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='subjects', type=d.T.array)]),
    withSubjectsMixin(subjects): { spec+: { subjects+: if std.isArray(v=subjects) then subjects else [subjects] } },
    '#withTlsFirst':: d.fn(help='"When true, the KV Store will initiate TLS before server INFO."', args=[d.arg(name='tlsFirst', type=d.T.boolean)]),
    withTlsFirst(tlsFirst): { spec+: { tlsFirst: tlsFirst } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
